### ISSUE TITLE
Multiple color boxes getting created

### ISSUE THREAD

**Issue by msimonelli** [recurser/jquery-simple-color#18]
Hello,

I'm currently experiencing an issue where part of a page can be reloaded via the .load function by the user clicking a reload icon.  The page contains javascript to initialize a simple-color div.  Everytime the page is reloaded this way, it creates another visible simple-color box... ie, if the page is reloaded by the user 3 times I will end up with 3 simple-color boxes.  Is there a way to check to see if a simple-color plugin has been created prior to creating it again, or destroying it before it's recreated each time?

**Comment by recurser** [comment]
Hi @msimonelli, apologies for the huge delay. You can try targeting the elements using the `:visible` selector. For example, instead of this:

```javascript
$('.simple_color').simpleColor();
```

... use this:

```javascript
$('.simple_color:visible').simpleColor();
```

The plugin sets the source input to invisible when it creates the color picker, so doing this should result in the color picker being set up only once.
